config/routes.rb
Rails.application.routes.draw do
  resources :memos
  devise_for :users
  resources :todos
  resources :users, only: [:index]
 
  get "/nums", to: "calcs#new"
  post "/nums", to: "calcs#exec"
  post "/nums2", to: "calcs#exec2"
  post "/nums3", to: "calcs#exec3"
  post "/nums4", to: "calcs#exec4"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  # Like１レコード = あるユーザーがあるtodoにいいねをした = 1つ分のいいね

  belongs_to :todo 
  belongs_to :user

  validates :user_id, uniqueness: {scope: :todo}

end

app/models/memo.rb
class Memo < ApplicationRecord

  validates :title, presence: true
end

app/models/tax.rb
class Tax < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord

  validates :text, presence: true, length: {maximum: 30}
  validates :priority, presence: true, inclusion: (1..5)

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos

  scope :search_email, ->(str) {
    where("email LIKE ?", "%#{str}%")
  }

  def name
    email.split("@")[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
  protected

  def terminal
    while(true) do
      print "terminal > "
      command = gets.chomp
      if command == "exit"
        break
      else
        begin
        p eval(command, binding)
        rescue => e
          p e
          next
        end
      end
    end
  end
end

app/controllers/calcs_controller.rb
class CalcsController < ApplicationController

  def new
  end


  def exec
    input = params[:input]

    @result = input.split(" ").map(&:to_i).sum
    render "new"

  end

  def exec2
    # 1. routes.rb編集 新しくルーティングを追加
    # 2. new.html.erbを編集 新しく追加したurlにアクセスする様に編集
    input = params[:input]


    # 足し算じゃなくて、掛け算する
    @result = input.split(" ").map(&:to_i)
    @result = @result[0] * @result[1]
    render "new"
  end


  def exec3
    input = params[:input].to_i # 100
    taxes = Tax.all
    @taxed_values = []
    taxes.each do |tax| #tax = <Tax id: 1, rate: 5, name: "5%", created_at: "2021-07-28 05:33:09", updated_at: "2021-07-28 05:33:09">
      @taxed_values.push(input * (1 + tax.rate / 100.0))
    end
  end

  def exec4
    @input = params[:input].to_i
    @taxes = Tax.all
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def index
    @todos = current_user.like_todos
  end


  def create
    Like.create(todo_id: params[:todo_id], user_id: current_user.id)
    redirect_to todo_path(params[:todo_id])
  end


  def destroy
    like = Like.find_by(todo_id: params[:id], user_id: current_user.id)
    like.destroy
    redirect_to todo_path(params[:id])
  end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /memos or /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1 or /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos or /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: "Memo was successfully created." }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1 or /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: "Memo was successfully updated." }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1 or /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: "Memo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def memo_params
      params.require(:memo).permit(:text, :title)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @todos = Todo.all
    # @todo = Todo.new
    # render :new
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id
    if @todo.save
      redirect_to @todo, notice: 'Todo was successfully created.'
    else
      flash.now[:alert] = "Missing create"
      render :new
    end
  end

  def update
    if @todo.update(todo_params)
      redirect_to @todo, notice: 'Todo was successfully updated.'
    else
      flash.now[:alert] = "Missing update"
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_url, notice: 'Todo was successfully destroyed.'
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:text, :priority)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/calcs/exec3.html.erb
<ul>

<% @taxed_values.each do |v| %>
  <li><%= v %></li>
<% end %>


<ul>

app/views/calcs/exec4.html.erb
<ul>

<% @taxes.each do |tax| %>
  <li><h2><%= @input * (1 + tax.rate / 100.0) %>円</h2></li>
<% end %>


<ul>
f.select_tagを使ってTaxを選択
選択肢た消費税と入力した値から税込値段

「rails f.select_tag」
form_with以外を使っている(form_tag, form_for)

app/views/calcs/new.html.erb
<h1>数字をスペース区切りで2つ入力して下さい</h1>



<%= form_with url: nums4_path, local: true do |f| %>

  <%= f.text_field "input" %>
  <%= f.submit "計算"%>

<% end %>

計算結果は<%= @result %>です

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspecSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link active" href="#">Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ストックしたTodoの一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Priority</th>
    </tr>
  </thead>

  <tbody>
    <% if @todos.count == 0 %>
      <p>ストックはまだありません</p>
    <% else %>
      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.text %></td>
          <td><%= todo.priority %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '一覧に戻る', todos_path %>

app/views/memos/_form.html.erb
<%= form_with(model: memo, local: true) do |form| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memos</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.text %></td>
        <td><%= memo.title %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @memo.text %>
</p>

<p>
  <strong>Title:</strong>
  <%= @memo.title %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<p>
  <%= link_to "ストックしたTodo", likes_path%>
</p>

<table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @todos.count == 0 %>
      <p>TODOが登録されていません</p>
    <% else %>
      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.text %></td>
          <td><%= todo.priority %></td>
          <td><%= link_to 'Show', todo %></td>
          <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
          <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<h1>Show Detail</h1>
<p>
  <strong>Text:</strong>
  <%= @todo.text %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>

<p>
  <% if @todo.likes.where(user_id: current_user.id).count == 0 %>
    <%= link_to "ストック(#{@todo.likes.count})", likes_path(todo_id: @todo.id), method: "post", class: "btn btn-primary"%>
  <% else %>
    <%= link_to "ストックを取り消す(#{@todo.likes.count})", like_path(@todo.id), method: "delete", class: "btn btn-danger"%>
  <% end %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>